name: ci

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        scala:
          - 2.13.11
          - 2.12.18

    steps:
      - uses: actions/checkout@v2

      - uses: coursier/cache-action@v5

      - uses: olafurpg/setup-scala@v10
        with:
          java-version: openjdk@1.11

      - name: test ${{ matrix.scala }}
        run: sbt ++${{ matrix.scala }} clean test
